spring.config.import=aws-parameterstore:/camp-health-app/prod/
management.endpoint.health.show-details=never
management.info.env.enabled=true
info.app.team-name=${TEAM-NAME}
logging.level.root=INFO
spring.jpa.hibernate.ddl-auto=validate
spring.cloud.aws.region.static=ap-northeast-2